cp /etc/nginx/extras/static/apple-touch-icon.png backend/open_webui/static/apple-touch-icon.png
cp /etc/nginx/extras/static/favicon-96x96.png backend/open_webui/static/favicon-96x96.png
cp /etc/nginx/extras/static/favicon-dark.png backend/open_webui/static/favicon-dark.png
cp /etc/nginx/extras/static/favicon.ico backend/open_webui/static/favicon.ico
cp /etc/nginx/extras/static/favicon.png backend/open_webui/static/favicon.png
cp /etc/nginx/extras/static/favicon.svg backend/open_webui/static/favicon.svg
cp /etc/nginx/extras/static/logo.png backend/open_webui/static/logo.png
cp /etc/nginx/extras/static/site.webmanifest backend/open_webui/static/site.webmanifest
cp /etc/nginx/extras/static/splash-dark.png backend/open_webui/static/splash-dark.png
cp /etc/nginx/extras/static/splash.png backend/open_webui/static/splash.png
cp /etc/nginx/extras/static/web-app-manifest-192x192.png backend/open_webui/static/web-app-manifest-192x192.png
cp /etc/nginx/extras/static/web-app-manifest-512x512.png backend/open_webui/static/web-app-manifest-512x512.png
cp /etc/nginx/extras/static/apple-touch-icon.png static/static/apple-touch-icon.png
cp /etc/nginx/extras/static/favicon-96x96.png static/static/favicon-96x96.png
cp /etc/nginx/extras/static/favicon-dark.png static/static/favicon-dark.png
cp /etc/nginx/extras/static/favicon.ico static/static/favicon.ico
cp /etc/nginx/extras/static/favicon.png static/static/favicon.png
cp /etc/nginx/extras/static/favicon.svg static/static/favicon.svg
cp /etc/nginx/extras/static/site.webmanifest static/static/site.webmanifest
cp /etc/nginx/extras/static/splash-dark.png static/static/splash-dark.png
cp /etc/nginx/extras/static/splash.png static/static/splash.png
cp /etc/nginx/extras/static/web-app-manifest-192x192.png static/static/web-app-manifest-192x192.png
cp /etc/nginx/extras/static/web-app-manifest-512x512.png static/static/web-app-manifest-512x512.png
cp /etc/nginx/extras/static/logo.png static/static/logo.png
